spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo_app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345677

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true

output:
  ansi:
    enabled: always

logging:
  level:
    org.hibernate.type: trace
    org.hibernate: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 8081
